name = "hono-cloudflare-pages"
compatibility_date = "2025-01-21"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[vars]
NAME = "Hono"

[[kv_namespaces]]
binding = "KV"
id = "c9dfc957b7a747a1962290c0e1f19311"


# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [[d1_databases]]
# binding = "DB" # i.e. available in your Worker on env.DB
# database_name = "todo"
# database_id = ""
# preview_database_id = "local-todo"

# [ai]
# binding = "AI"
